// ON START
export const GET_NET_INFO_REQUEST = 'GET_NET_INFO_REQUEST';
export const GET_NET_INFO_REQUEST_SUCCESS = 'GET_NET_INFO_REQUEST_SUCCESS';
export const GET_NET_INFO_REQUEST_FAIL = 'GET_NET_INFO_REQUEST_FAIL';

// HOME
export const GET_MOVIE_LIST_REQUEST = 'GET_MOVIE_LIST_REQUEST';
export const GET_MOVIE_LIST_REQUEST_SUCCESS = 'GET_MOVIE_LIST_REQUEST_SUCCESS';
export const GET_MOVIE_LIST_REQUEST_FAIL = 'GET_MOVIE_LIST_REQUEST_FAIL';
export const GET_DATA_MOVIE_FROM_STORAGE_REQUEST =
  'GET_DATA_MOVIE_FROM_STORAGE_REQUEST';
export const GET_DATA_MOVIE_FROM_STORAGE_REQUEST_SUCCESS =
  'GET_DATA_MOVIE_FROM_STORAGE_REQUEST_SUCCESS';
export const GET_DATA_MOVIE_FROM_STORAGE_REQUEST_FAIL =
  'GET_DATA_MOVIE_FROM_STORAGE_REQUEST_FAIL';
